#!/usr/bin/env bash
set -euo pipefail

###############################################################################
# Stage 05 – Vicidial Core (EL9 – Golden)
# Purpose:
#   - Install Vicidial core files
#   - Generate astguiclient.conf (DBI-safe)
#   - Validate database connectivity via DBI (MariaDB)
#   - Start Vicidial cron & services
###############################################################################

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALLER_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

source "${INSTALLER_ROOT}/lib/common.sh"

require_root
require_command perl
require_command mysql



STAGE_NAME="Stage_05"
stage_begin "${STAGE_NAME}"

log "=== Stage 05: Vicidial Core (EL9) ==="

###############################################################################
# OS Guard
###############################################################################
check_el9

###############################################################################
# Required Variables
###############################################################################
require_vars \
  VICIDIAL_DB_HOST \
  VICIDIAL_DB_NAME \
  VICIDIAL_DB_USER \
  VICIDIAL_DB_PASS \
  VICIDIAL_AST_USER \
  VICIDIAL_AST_GROUP

###############################################################################
# Database Preflight (Authoritative)
###############################################################################
log "Running database preflight checks (DBI/MariaDB)"
db_preflight

###############################################################################
# Install Vicidial Core
###############################################################################
log "Installing Vicidial core files"

if [[ ! -d /usr/share/astguiclient ]]; then
  fail "Vicidial core directory not found. Ensure Stage 04 completed successfully."
fi

###############################################################################
# Detect MariaDB Socket Dynamically
###############################################################################
DB_SOCKET="$(get_mariadb_socket)"
log "Detected MariaDB socket: ${DB_SOCKET}"

###############################################################################
# Generate astguiclient.conf (EL9-Safe)
###############################################################################
ASTGUI_CONF="/etc/astguiclient.conf"

log "Generating ${ASTGUI_CONF}"

cat > "${ASTGUI_CONF}" <<EOF
#------------------------------------------------------------------------------
# astguiclient.conf (EL9 – Golden)
#------------------------------------------------------------------------------
# Generated by Vicidial Installer – DO NOT EDIT MANUALLY
#------------------------------------------------------------------------------

VARDB_server=${VICIDIAL_DB_HOST}
VARDB_database=${VICIDIAL_DB_NAME}
VARDB_user=${VICIDIAL_DB_USER}
VARDB_pass=${VICIDIAL_DB_PASS}
VARDB_port=3306
VARDB_socket=${DB_SOCKET}

VARDB_custom_database=${VICIDIAL_DB_NAME}
VARDB_custom_user=${VICIDIAL_DB_USER}
VARDB_custom_pass=${VICIDIAL_DB_PASS}

PATHhome=/usr/share/astguiclient
PATHlogs=/var/log/astguiclient
PATHagi=/var/lib/asterisk/agi-bin
PATHweb=/var/www/html
PATHsounds=/var/lib/asterisk/sounds
PATHmonitor=/var/spool/asterisk/monitor
PATHDONEmonitor=/var/spool/asterisk/monitorDONE

ASTuser=${VICIDIAL_AST_USER}
ASTgroup=${VICIDIAL_AST_GROUP}

# System tuning
VARserver_ip=127.0.0.1
EOF

chmod 600 "${ASTGUI_CONF}"
chown root:root "${ASTGUI_CONF}"

log "astguiclient.conf generated successfully"

###############################################################################
# Validate Perl Can Load Vicidial Libraries
###############################################################################
log "Validating Vicidial Perl environment"

perl -e '
  use lib "/usr/share/astguiclient";
  use Time::HiRes;
  print "Perl Vicidial environment OK\n";
' >/dev/null

###############################################################################
# Setup Vicidial Cron Jobs
###############################################################################
log "Installing Vicidial cron jobs"

if [[ -f /usr/share/astguiclient/AST_cron_jobs.pl ]]; then
  perl /usr/share/astguiclient/AST_cron_jobs.pl --install
else
  fail "AST_cron_jobs.pl not found"
fi

###############################################################################
# Permissions & Ownership
###############################################################################
log "Fixing Vicidial permissions"

mkdir -p /var/log/astguiclient
chown -R "${VICIDIAL_AST_USER}:${VICIDIAL_AST_GROUP}" /var/log/astguiclient
chmod -R 755 /var/log/astguiclient

###############################################################################
# Final Sanity Check (Non-DB)
##########################################################################
# -----------------------------------------------------------------------------
# Completion
# -----------------------------------------------------------------------------
log_success "Stage 05 completed – Vicidial core installed successfully"
stage_finish "${STAGE_NAME}"